title: Mon Blog
copyright: "Â© [PaperMod Contributors](https://github.com/adityatelange/hugo-PaperMod/graphs/contributors)"
theme: [PaperMod]
baseURL: "https://nyobemichel.me/"
languageCode: "fr-fr"
googleAnalytics: G-S1YCLX5573

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
mainsections: ["posts", "papermod"]

minify:
  disableXML: true

pagination:
  disableAliases: false
  pagerSize: 5

defaultContentLanguage: fr
defaultContentLanguageInSubdir: false

languages:
  fr:
    languageName: ":fr:"
    weight: 1
    title: larass0x04
    taxonomies:
      category: categories
      tag: tags
    menu:
      main:
        - name: Moi
          url: about
          weight: 1
        - name: Archive
          url: archives/
          weight: 5
        - name: Categories
          url: categories
          weight: 10
        - name: Tous les articles
          url: posts/
          weight: 3
        - name: Search
          url: search/
          weight: 15
    params:
      languageAltTitle: French
      profileMode:
        enabled: true
        title: Michel Nyobe
        imageUrl: "https://raw.githubusercontent.com/googlefonts/noto-emoji/master/svg/emoji_u1f9d1_1f3fb_200d_1f4bb.svg"
        imageTitle: ProfileMode image
        subtitle: "â˜„ï¸ Active Directory Attack And Defense  | â˜ï¸ Cloud Hacking | IAM  | ðŸ“± Offensive security "
        buttons:
          - name: Blog
            url: posts
          - name: Profile Mode
            url: https://github.com/michelnyobe

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  description: "Mon Blog Personnel sur la Cybersecurite"
  author: "Michel NYOBE"

  defaultTheme: auto
  ShowShareButtons: true
  hideFooter: true
  ShowReadingTime: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true
  images: ["images/papermod-cover.png"]

  profileMode:
    enabled: false
    title: PaperMod
    imageUrl: "#"
    imageTitle: my image
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags

  homeInfoParams:
    Title: "Moon Nouveau BLOG"
    Content: >
      ðŸ‘‹ Bienvenue sur Mon site dediee a la Cybersecurite  !

  socialIcons:
    - name: github
      title: Voir la source sur Github
      url: "https://github.com/michelnyobe"
    - name: Discord
      title: Rejoignez la communautÃ© Discord
      url: "https://discord.gg/TbqtHywJ"
    - name: X
      title: Rejoignez-moi sur X
      url: "https://x.com/larass0x04"
    - name: LinkedIn
      title: Connectez-vous avec moi sur LinkedIn
      url: "http://www.linkedin.com/in/nyobemichel"
    - name: YouTube
      title: Abonnez-vous Ã  ma chaÃ®ne YouTube
      url: "http://www.youtube.com/@Larass0x04"

  assets:
    disableHLJS: true

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false

services:
  instagram:
    disableInlineCSS: true
  x:
    disableInlineCSS: true
